# -*- coding: utf-8 -*-
"""scrapper-aux.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r_eyZADJ52Jj1bNx0j0vB3kZe6RBxReC
"""

#!pip install requests beautifulsoup4 pandas simplejson

#!/usr/bin/env python3

import requests
from bs4 import BeautifulSoup
import pandas as pd
import json
import sys

''''''''''''''''''''''''''''''''''''''''''''''''''''''
''' Limpieza del DataFrame '''
''''''''''''''''''''''''''''''''''''''''''''''''''''''

def default(df: pd.DataFrame) -> pd.DataFrame:
  df = df.drop(columns=[5])
  df[2] = df[2].str.capitalize()
  df[3] = df[3].apply(lambda x: depto[x] if x in depto else x)
  df[4] = df[4].apply(lambda x: int(x) if x.isdigit() else x)
  return df

def limpiar_df(df: pd.DataFrame, carrera: str) -> pd.DataFrame:
  df = df.replace('–', '-', regex=True)

  df[0] = df[0].str.replace('» ', '', regex=False)
  df[0] = df[0].apply(lambda x: int(x) if x.isdigit() else x)

  df[len(df.columns)-1] = df[len(df.columns)-1].apply(
      lambda x: [int(s) for s in x.split('-') if s.isdigit()] if isinstance(x, str) else x
      )

  if carrera in ["actuario", "administracion", "economia"]:
    df = default(df)

  elif carrera == "analisis-datos":
    df = df.drop(columns=[4, 5, 6])
    df[3] = df[3].apply(lambda x: int(x) if x.isdigit() else x)
    df.insert(3, "x", "")

  elif carrera == "contador":
    if len(df.columns) == 6:
        df[2] = df[2].apply(lambda x: int(x) if x.isdigit() else x)
        df = df.drop(columns=[3, 4])
        df.insert(2, "x", "")
        df.insert(3, "y", "")
    else:
        df = default(df)

  elif carrera == "sistemas":
    if len(df.columns) < 6:
      return None
    if len(df.columns) == 7:
      df = df.drop(columns=[5])
    df[2] = df[2].str.capitalize()
    df[3] = df[3].apply(lambda x: depto[x] if x in depto else x)
    df[4] = df[4].apply(lambda x: int(x) if x.isdigit() else x)

  return df

''''''''''''''''''''''''''''''''''''''''''''''''''''''
''' Parsear data scrapeada a DataFrame '''
''''''''''''''''''''''''''''''''''''''''''''''''''''''

def parsear_datos_a_df(resultado_scrap: list) -> pd.DataFrame:
  filas_totales = []
  fila_actual = []

  for item in resultado_scrap:
      if item.startswith('»'):
          if fila_actual:
              filas_totales.append(fila_actual)
          fila_actual = [item]
      else:
          fila_actual.append(item)

  if fila_actual:
      filas_totales.append(fila_actual)

  filas_totales = [fila for fila in filas_totales if fila[0].startswith('»')]

  if not filas_totales:
      return pd.DataFrame()

  longitud_referencia = len(filas_totales[0])
  filas_totales = [fila[:longitud_referencia] for fila in filas_totales]

  header = [i for i in range(longitud_referencia)]
  df_tabla = pd.DataFrame(filas_totales, columns=header)

  return df_tabla

''''''''''''''''''''''''''''''''''''''''''''''''''''''
''' Exportar a JSON '''
''''''''''''''''''''''''''''''''''''''''''''''''''''''

def exportar_a_json(lista_a_guardar: list, nombre_archivo: str) -> None:
    formato_json: list = [elem for sublista in lista_a_guardar for elem in sublista]

    with open(f"{nombre_archivo}.json", "w", encoding="utf-8") as f:
        json.dump(formato_json, f, ensure_ascii=False, indent=4)

    print(f"Se ha exportado el archivo {nombre_archivo}.json")

depto: dict = {"M": "Matemática", "E": "Economía", "H": "Humanidades",
                "D": "Derecho", "A": "Administración", "T": "Tributación",
                "C": "Contabilidad", "S": "Sistemas"}

def main():
  carrera: str = "> Modificar"
  if carrera not in ["actuario", "administracion", "analisis-datos", "contador",
                    "economia", "sistemas"]:
      return

  url: str = f"https://www.economicas.uba.ar/carreras/{carrera}/"
  dict_filas: list = []

  response = requests.get(url, verify=False)
  response.encoding = 'utf-8'

  if response.status_code == 200:
      soup = BeautifulSoup(response.text, 'html.parser')
      tablas = soup.find_all(class_="table table-bordered table-striped")

      for tabla in tablas:
          contenido: list = [td.get_text(strip=True).replace('\xa0', ' ') for td in tabla.find_all('td')]
          df_tabla: pd.DataFrame = parsear_datos_a_df(contenido)
          df_tabla = limpiar_df(df_tabla, f"{carrera}")
          if df_tabla is not None:
            df_tabla.columns = ["codigo", "materia", "caracter", "departamento", "hs_semanales", "correlativas"]
            dict_filas.append(df_tabla.to_dict(orient="records"))

  else:
      print("Error al acceder a la página.", response.status_code)

  exportar_a_json(dict_filas, f"{carrera}")

main()